### ISSUE TITLE
IOError: Unable to open file (unable to open file: name = 'weights/mobilenet_weights.h5'

### ISSUE THREAD

**Issue by DmitryKey** [Diyago/Machine-Learning-scripts#1]
**Describe the bug**
IOError: Unable to open file (unable to open file: name = 'weights/mobilenet_weights.h5'
when running:

    python evaluate_mobilenet.py -dir dir_with_single_jpg_file

**To Reproduce**
1. See description

**Desktop (please complete the following information):**
 - OSX
 - keras 2.2.2

**Comment by Diyago** [comment]
As you can from error description file  mobilenet_weights.h5 not found. It is just weights from pretrained NN, which can be googled or can be found here on github.

For example here: 
https://github.com/titu1994/neural-image-assessment/tree/master/weights

Please reopen issue, if you are still facing problems
