### ISSUE TITLE
nn_image_features throws SyntaxError

### ISSUE THREAD

**Issue by DmitryKey** [Diyago/Machine-Learning-scripts#2]
**Describe the bug**
    File "nn_image_features.py", line 108
        raise ValueError(f'Got incorrect DenseNet model type ({model_type}).')
                                                                        ^
SyntaxError: invalid syntax

**Comment by Diyago** [comment]
As error suggests you have wrong DenseNet model. Check this: model_name[len('densenet')

**Comment by DmitryKey** [comment]
Thanks. Actually I have not changed any source code and not much familiar with it. Only trying to repro your solution, so thanks for patience! :)

The root issue likely is that I assumed this file to be executable, but it is not. Did you use this file to extract image features?

**Comment by Diyago** [comment]
Sometime it is, sometime is not executable

Yes, I did

I think this is about understanding, not reproducing results

**Comment by DmitryKey** [comment]
Agree on understanding: my approach right now is a bit adhoc with sole target of reproducing. But looks like will need to educate myself more on this specific solution.
